-- =============================================
-- Water Meter Collection System - Database Tables
-- =============================================

-- 1. PROVINCE / CITY (Tỉnh/TP)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_PROVINCE')
CREATE TABLE WM_PROVINCE (
    PROVINCE_ID INT PRIMARY KEY IDENTITY(1,1),
    PROVINCE_CODE VARCHAR(20) NOT NULL,
    PROVINCE_NAME NVARCHAR(100) NOT NULL,
    STATUS INT DEFAULT 1, -- 1: Active, 0: Inactive
    CREATED_DATE DATETIME DEFAULT GETDATE()
);

-- 2. DISTRICT (Quận/Huyện)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_DISTRICT')
CREATE TABLE WM_DISTRICT (
    DISTRICT_ID INT PRIMARY KEY IDENTITY(1,1),
    DISTRICT_CODE VARCHAR(20) NOT NULL,
    DISTRICT_NAME NVARCHAR(100) NOT NULL,
    PROVINCE_ID INT NOT NULL,
    STATUS INT DEFAULT 1,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PROVINCE_ID) REFERENCES WM_PROVINCE(PROVINCE_ID)
);

-- 3. WARD (Phường/Xã)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_WARD')
CREATE TABLE WM_WARD (
    WARD_ID INT PRIMARY KEY IDENTITY(1,1),
    WARD_CODE VARCHAR(20) NOT NULL,
    WARD_NAME NVARCHAR(100) NOT NULL,
    DISTRICT_ID INT NOT NULL,
    STATUS INT DEFAULT 1,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (DISTRICT_ID) REFERENCES WM_DISTRICT(DISTRICT_ID)
);

-- 4. ZONE (Khu vực)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_ZONE')
CREATE TABLE WM_ZONE (
    ZONE_ID INT PRIMARY KEY IDENTITY(1,1),
    ZONE_CODE VARCHAR(20) NOT NULL,
    ZONE_NAME NVARCHAR(100) NOT NULL,
    WARD_ID INT NOT NULL,
    STATUS INT DEFAULT 1,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (WARD_ID) REFERENCES WM_WARD(WARD_ID)
);

-- 5. CLUSTER (Cụm)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_CLUSTER')
CREATE TABLE WM_CLUSTER (
    CLUSTER_ID INT PRIMARY KEY IDENTITY(1,1),
    CLUSTER_CODE VARCHAR(20) NOT NULL,
    CLUSTER_NAME NVARCHAR(100) NOT NULL,
    ZONE_ID INT NOT NULL,
    STATUS INT DEFAULT 1,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ZONE_ID) REFERENCES WM_ZONE(ZONE_ID)
);

-- 6. CUSTOMER (Khách hàng)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_CUSTOMER')
CREATE TABLE WM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMER_CODE VARCHAR(20) NOT NULL UNIQUE,
    CUSTOMER_NAME NVARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ADDRESS NVARCHAR(255),
    PROVINCE_ID INT,
    DISTRICT_ID INT,
    WARD_ID INT,
    ZONE_ID INT,
    CLUSTER_ID INT,
    CUSTOMER_TYPE INT DEFAULT 1, -- 1: Cá nhân, 2: Doanh nghiệp
    STATUS INT DEFAULT 1,
    CONTRACT_DATE DATE,
    CREATED_DATE DATETIME DEFAULT GETDATE()
);

-- 7. WATER METER (Đồng hồ nước)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_WATER_METER')
CREATE TABLE WM_WATER_METER (
    WATER_METER_ID INT PRIMARY KEY IDENTITY(1,1),
    METER_CODE VARCHAR(20) NOT NULL UNIQUE,
    METER_SERIAL VARCHAR(50),
    MODEL VARCHAR(50),
    CUSTOMER_ID INT NOT NULL,
    PROVINCE_ID INT,
    DISTRICT_ID INT,
    WARD_ID INT,
    ZONE_ID INT,
    CLUSTER_ID INT,
    GATEWAY_ID INT,
    LATITUDE DECIMAL(10,7),
    LONGITUDE DECIMAL(10,7),
    INSTALL_DATE DATE,
    LAST_READING DECIMAL(10,2),
    LAST_READING_DATE DATETIME,
    STATUS INT DEFAULT 1, -- 1: Hoạt động, 0: Ngừng, 2: Lỗi
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES WM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PROVINCE_ID) REFERENCES WM_PROVINCE(PROVINCE_ID),
    FOREIGN KEY (DISTRICT_ID) REFERENCES WM_DISTRICT(DISTRICT_ID),
    FOREIGN KEY (WARD_ID) REFERENCES WM_WARD(WARD_ID),
    FOREIGN KEY (ZONE_ID) REFERENCES WM_ZONE(ZONE_ID),
    FOREIGN KEY (CLUSTER_ID) REFERENCES WM_CLUSTER(CLUSTER_ID)
);

-- 8. READING (Chỉ số)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_READING')
CREATE TABLE WM_READING (
    READING_ID INT PRIMARY KEY IDENTITY(1,1),
    WATER_METER_ID INT NOT NULL,
    READING_VALUE DECIMAL(10,2) NOT NULL,
    READING_DATE DATETIME NOT NULL,
    READING_TYPE INT DEFAULT 1, -- 1: Định kỳ, 2: Thủ công, 3: Tự động
    NOTES NVARCHAR(255),
    CREATED_BY VARCHAR(50),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (WATER_METER_ID) REFERENCES WM_WATER_METER(WATER_METER_ID)
);

-- 9. GATEWAY
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_GATEWAY')
CREATE TABLE WM_GATEWAY (
    GATEWAY_ID INT PRIMARY KEY IDENTITY(1,1),
    GATEWAY_CODE VARCHAR(20) NOT NULL UNIQUE,
    GATEWAY_NAME NVARCHAR(100),
    IP_ADDRESS VARCHAR(50),
    PORT INT DEFAULT 8080,
    PROVINCE_ID INT,
    DISTRICT_ID INT,
    WARD_ID INT,
    LATITUDE DECIMAL(10,7),
    LONGITUDE DECIMAL(10,7),
    SIGNAL_STRENGTH INT DEFAULT -50, -- dBm
    LAST_ONLINE DATETIME,
    STATUS INT DEFAULT 1, -- 1: Online, 0: Offline
    INSTALL_DATE DATE,
    CREATED_DATE DATETIME DEFAULT GETDATE()
);

-- 10. INVOICE (Hóa đơn)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_INVOICE')
CREATE TABLE WM_INVOICE (
    INVOICE_ID INT PRIMARY KEY IDENTITY(1,1),
    INVOICE_CODE VARCHAR(20) NOT NULL UNIQUE,
    CUSTOMER_ID INT NOT NULL,
    INVOICE_DATE DATE NOT NULL,
    PERIOD_FROM DATE NOT NULL,
    PERIOD_TO DATE NOT NULL,
    PREVIOUS_READING DECIMAL(10,2),
    CURRENT_READING DECIMAL(10,2),
    CONSUMPTION DECIMAL(10,2),
    UNIT_PRICE DECIMAL(10,2),
    TOTAL_AMOUNT DECIMAL(15,2),
    DUE_DATE DATE,
    STATUS INT DEFAULT 1, -- 1: Chờ thanh toán, 2: Quá hạn, 3: Đã thanh toán
    PAID_DATE DATE,
    PAYMENT_METHOD VARCHAR(50),
    NOTES NVARCHAR(255),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES WM_CUSTOMER(CUSTOMER_ID)
);

-- 11. ALERT (Cảnh báo)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_ALERT')
CREATE TABLE WM_ALERT (
    ALERT_ID INT PRIMARY KEY IDENTITY(1,1),
    ALERT_TYPE INT NOT NULL, -- 1: Mất kết nối, 2: Pin yếu, 3: Tiêu thụ bất thường, 4: Rò rỉ, 5: Thông tin
    ALERT_MESSAGE NVARCHAR(255) NOT NULL,
    ALERT_TIME DATETIME NOT NULL,
    RELATED_ID INT,
    RELATED_TYPE VARCHAR(20), -- 'meter', 'gateway', 'system'
    IS_READ INT DEFAULT 0,
    CREATED_DATE DATETIME DEFAULT GETDATE()
);

-- 12. MAINTENANCE (Bảo trì)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'WM_MAINTENANCE')
CREATE TABLE WM_MAINTENANCE (
    MAINTENANCE_ID INT PRIMARY KEY IDENTITY(1,1),
    WORK_ORDER_CODE VARCHAR(20) NOT NULL UNIQUE,
    TITLE NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(500),
    METER_ID INT,
    PRIORITY INT DEFAULT 2, -- 1: Cao, 2: Trung bình, 3: Thấp
    SCHEDULED_DATE DATE,
    STATUS INT DEFAULT 1, -- 1: Mới tạo, 2: Đang xử lý, 3: Hoàn thành, 4: Hủy
    ASSIGNED_TO VARCHAR(100),
    COMPLETED_DATE DATE,
    NOTES NVARCHAR(500),
    CREATED_BY VARCHAR(50),
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (METER_ID) REFERENCES WM_WATER_METER(WATER_METER_ID)
);

-- =============================================
-- Insert Sample Data
-- =============================================

-- Insert Provinces
INSERT INTO WM_PROVINCE (PROVINCE_CODE, PROVINCE_NAME) VALUES ('HCM', N'TP. Hồ Chí Minh');
INSERT INTO WM_PROVINCE (PROVINCE_CODE, PROVINCE_NAME) VALUES ('DN', N'Tỉnh Đồng Nai');
INSERT INTO WM_PROVINCE (PROVINCE_CODE, PROVINCE_NAME) VALUES ('BD', N'Tỉnh Bình Dương');

-- Insert Districts
INSERT INTO WM_DISTRICT (DISTRICT_CODE, DISTRICT_NAME, PROVINCE_ID) VALUES ('Q1', N'Quận 1', 1);
INSERT INTO WM_DISTRICT (DISTRICT_CODE, DISTRICT_NAME, PROVINCE_ID) VALUES ('Q3', N'Quận 3', 1);
INSERT INTO WM_DISTRICT (DISTRICT_CODE, DISTRICT_NAME, PROVINCE_ID) VALUES ('Q5', N'Quận 5', 1);
INSERT INTO WM_DISTRICT (DISTRICT_CODE, DISTRICT_NAME, PROVINCE_ID) VALUES ('Q7', N'Quận 7', 1);
INSERT INTO WM_DISTRICT (DISTRICT_CODE, DISTRICT_NAME, PROVINCE_ID) VALUES ('BT', N'Quận Bình Thạnh', 1);

-- Insert Wards
INSERT INTO WM_WARD (WARD_CODE, WARD_NAME, DISTRICT_ID) VALUES ('P1', N'Phường Bến Nghé', 1);
INSERT INTO WM_WARD (WARD_CODE, WARD_NAME, DISTRICT_ID) VALUES ('P2', N'Phường Bến Thành', 1);
INSERT INTO WM_WARD (WARD_CODE, WARD_NAME, DISTRICT_ID) VALUES ('P8', N'Phường 8', 2);
INSERT INTO WM_WARD (WARD_CODE, WARD_NAME, DISTRICT_ID) VALUES ('P9', N'Phường 9', 2);
INSERT INTO WM_WARD (WARD_CODE, WARD_NAME, DISTRICT_ID) VALUES ('P11', N'Phường 11', 3);

-- Insert Zones
INSERT INTO WM_ZONE (ZONE_CODE, ZONE_NAME, WARD_ID) VALUES ('K1', N'Khu vực 1', 1);
INSERT INTO WM_ZONE (ZONE_CODE, ZONE_NAME, WARD_ID) VALUES ('K2', N'Khu vực 2', 1);
INSERT INTO WM_ZONE (ZONE_CODE, ZONE_NAME, WARD_ID) VALUES ('K3', N'Khu vực 3', 2);

-- Insert Clusters
INSERT INTO WM_CLUSTER (CLUSTER_CODE, CLUSTER_NAME, ZONE_ID) VALUES ('C1', N'Cụm 1', 1);
INSERT INTO WM_CLUSTER (CLUSTER_CODE, CLUSTER_NAME, ZONE_ID) VALUES ('C2', N'Cụm 2', 1);
INSERT INTO WM_CLUSTER (CLUSTER_CODE, CLUSTER_NAME, ZONE_ID) VALUES ('C3', N'Cụm 3', 2);

-- Insert Sample Customers
INSERT INTO WM_CUSTOMER (CUSTOMER_CODE, CUSTOMER_NAME, PHONE, ADDRESS, PROVINCE_ID, DISTRICT_ID, WARD_ID, ZONE_ID, CLUSTER_ID, CUSTOMER_TYPE, CONTRACT_DATE)
VALUES ('KH001', N'Nguyễn Văn A', '0912345678', N'123 Lê Lợi, Q.1, TP.HCM', 1, 1, 1, 1, 1, 1, '2024-01-15');
INSERT INTO WM_CUSTOMER (CUSTOMER_CODE, CUSTOMER_NAME, PHONE, ADDRESS, PROVINCE_ID, DISTRICT_ID, WARD_ID, ZONE_ID, CLUSTER_ID, CUSTOMER_TYPE, CONTRACT_DATE)
VALUES ('KH002', N'Trần Thị B', '0912345679', N'456 Nguyễn Huệ, Q.1, TP.HCM', 1, 1, 1, 1, 1, 1, '2024-01-20');
INSERT INTO WM_CUSTOMER (CUSTOMER_CODE, CUSTOMER_NAME, PHONE, ADDRESS, PROVINCE_ID, DISTRICT_ID, WARD_ID, ZONE_ID, CLUSTER_ID, CUSTOMER_TYPE, CONTRACT_DATE)
VALUES ('KH003', N'Lê Văn C', '0912345680', N'789 Pasteur, Q.1, TP.HCM', 1, 1, 2, 2, 2, 1, '2023-12-10');

-- Insert Sample Water Meters
INSERT INTO WM_WATER_METER (METER_CODE, METER_SERIAL, MODEL, CUSTOMER_ID, PROVINCE_ID, DISTRICT_ID, WARD_ID, ZONE_ID, CLUSTER_ID, LATITUDE, LONGITUDE, INSTALL_DATE, LAST_READING, STATUS)
VALUES ('MTR001', 'SN12345', 'Elster', 1, 1, 1, 1, 1, 1, 10.7769, 106.6989, '2024-01-15', 125.5, 1);
INSERT INTO WM_WATER_METER (METER_CODE, METER_SERIAL, MODEL, CUSTOMER_ID, PROVINCE_ID, DISTRICT_ID, WARD_ID, ZONE_ID, CLUSTER_ID, LATITUDE, LONGITUDE, INSTALL_DATE, LAST_READING, STATUS)
VALUES ('MTR002', 'SN12346', 'Itron', 2, 1, 1, 1, 1, 1, 10.7770, 106.6990, '2024-01-20', 89.2, 1);
INSERT INTO WM_WATER_METER (METER_CODE, METER_SERIAL, MODEL, CUSTOMER_ID, PROVINCE_ID, DISTRICT_ID, WARD_ID, ZONE_ID, CLUSTER_ID, LATITUDE, LONGITUDE, INSTALL_DATE, LAST_READING, STATUS)
VALUES ('MTR003', 'SN12347', 'Sensus', 3, 1, 1, 2, 2, 2, 10.7780, 106.7000, '2023-12-10', 234.8, 1);

-- Insert Sample Gateways
INSERT INTO WM_GATEWAY (GATEWAY_CODE, GATEWAY_NAME, IP_ADDRESS, PORT, PROVINCE_ID, DISTRICT_ID, WARD_ID, SIGNAL_STRENGTH, STATUS)
VALUES ('GW001', 'Gateway Q1', '192.168.1.100', 8080, 1, 1, 1, -55, 1);
INSERT INTO WM_GATEWAY (GATEWAY_CODE, GATEWAY_NAME, IP_ADDRESS, PORT, PROVINCE_ID, DISTRICT_ID, WARD_ID, SIGNAL_STRENGTH, STATUS)
VALUES ('GW002', 'Gateway Q3', '192.168.1.101', 8080, 1, 2, 3, -65, 1);

-- Insert Sample Invoices
INSERT INTO WM_INVOICE (INVOICE_CODE, CUSTOMER_ID, INVOICE_DATE, PERIOD_FROM, PERIOD_TO, PREVIOUS_READING, CURRENT_READING, CONSUMPTION, UNIT_PRICE, TOTAL_AMOUNT, DUE_DATE, STATUS)
VALUES ('HD202604001', 1, '2026-04-01', '2026-03-01', '2026-03-31', 115.5, 125.5, 10.0, 15000, 150000, '2026-04-15', 1);
INSERT INTO WM_INVOICE (INVOICE_CODE, CUSTOMER_ID, INVOICE_DATE, PERIOD_FROM, PERIOD_TO, PREVIOUS_READING, CURRENT_READING, CONSUMPTION, UNIT_PRICE, TOTAL_AMOUNT, DUE_DATE, STATUS)
VALUES ('HD202604002', 2, '2026-04-01', '2026-03-01', '2026-03-31', 79.2, 89.2, 10.0, 15000, 150000, '2026-04-15', 1);
INSERT INTO WM_INVOICE (INVOICE_CODE, CUSTOMER_ID, INVOICE_DATE, PERIOD_FROM, PERIOD_TO, PREVIOUS_READING, CURRENT_READING, CONSUMPTION, UNIT_PRICE, TOTAL_AMOUNT, DUE_DATE, STATUS)
VALUES ('HD202604003', 3, '2026-04-01', '2026-03-01', '2026-03-31', 224.8, 234.8, 10.0, 15000, 150000, '2026-04-15', 3);

-- Insert Sample Alerts
INSERT INTO WM_ALERT (ALERT_TYPE, ALERT_MESSAGE, ALERT_TIME, RELATED_ID, RELATED_TYPE, IS_READ)
VALUES (1, N'Mất kết nối đồng hồ MTR003 > 24h', GETDATE(), 3, 'meter', 0);
INSERT INTO WM_ALERT (ALERT_TYPE, ALERT_MESSAGE, ALERT_TIME, RELATED_ID, RELATED_TYPE, IS_READ)
VALUES (2, N'Pin yếu đồng hồ MTR002 (< 20%)', GETDATE(), 2, 'meter', 0);
INSERT INTO WM_ALERT (ALERT_TYPE, ALERT_MESSAGE, ALERT_TIME, RELATED_ID, RELATED_TYPE, IS_READ)
VALUES (3, N'Tiêu thụ bất thường đồng hồ MTR001', GETDATE(), 1, 'meter', 1);
INSERT INTO WM_ALERT (ALERT_TYPE, ALERT_MESSAGE, ALERT_TIME, RELATED_ID, RELATED_TYPE, IS_READ)
VALUES (5, N'Cập nhật firmware thành công', GETDATE(), 1, 'meter', 1);

-- =============================================
-- RPT_VOLUME — Báo cáo sản lượng tiêu thụ
-- =============================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'RPT_VOLUME')
CREATE TABLE RPT_VOLUME (
    RPT_ID      INT           PRIMARY KEY IDENTITY(1,1),
    NAME        NVARCHAR(200) NOT NULL,
    CREATED     DATETIME      DEFAULT GETDATE(),
    USER_ID     INT           NULL,
    START_DATE  DATE          NOT NULL,
    PERIOD_NUM  INT           NOT NULL DEFAULT 12,
    TIME_RECORD VARCHAR(10)   NOT NULL DEFAULT 'MONTH'  -- MONTH | DAY | YEAR
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'RPT_VOLUME_GROUP')
CREATE TABLE RPT_VOLUME_GROUP (
    GROUP_ID    INT           PRIMARY KEY IDENTITY(1,1),
    RPT_ID      INT           NOT NULL REFERENCES RPT_VOLUME(RPT_ID) ON DELETE CASCADE,
    NAME        NVARCHAR(200) NOT NULL,
    ORDER_NO    INT           DEFAULT 0
);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'RPT_VOLUME_GROUP_METER')
CREATE TABLE RPT_VOLUME_GROUP_METER (
    ID          INT           PRIMARY KEY IDENTITY(1,1),
    GROUP_ID    INT           NOT NULL REFERENCES RPT_VOLUME_GROUP(GROUP_ID) ON DELETE CASCADE,
    METER_NO    VARCHAR(50)   NOT NULL,
    ORDER_NO    INT           DEFAULT 0,
    STATE       INT           DEFAULT 1
);

PRINT N'Database tables created successfully!';