-- ================================================================
-- INDEXES TỐI ƯU HIỆU NĂNG
-- Chạy file này một lần trên SQL Server để tăng tốc query đáng kể.
-- OUTER APPLY TOP 1 và range queries sẽ seek thay vì full scan.
-- ================================================================

-- HIS_DATA_METER: tối ưu cho OUTER APPLY TOP 1 và range queries 30 ngày
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'IX_HIS_DATA_METER_METER_DATATIME'
    AND object_id = OBJECT_ID('HIS_DATA_METER')
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_HIS_DATA_METER_METER_DATATIME
    ON HIS_DATA_METER (METER_NO, DATA_TIME DESC)
    INCLUDE (FLOW, PRESSURE, ACTIVE_TOTAL);
  PRINT 'Created IX_HIS_DATA_METER_METER_DATATIME';
END

-- HIS_INSTANT_METER: tối ưu cho OUTER APPLY TOP 1
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'IX_HIS_INSTANT_METER_METER_REALTIME'
    AND object_id = OBJECT_ID('HIS_INSTANT_METER')
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_HIS_INSTANT_METER_METER_REALTIME
    ON HIS_INSTANT_METER (METER_NO, REALTIME DESC)
    INCLUDE (SIGNAL, REMAIN_BATTERY, TEMPERATURE, GATEWAY_NO);
  PRINT 'Created IX_HIS_INSTANT_METER_METER_REALTIME';
END

-- HIS_INSTANT_METER: tối ưu cho monthly events count query
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'IX_HIS_INSTANT_METER_CREATED'
    AND object_id = OBJECT_ID('HIS_INSTANT_METER')
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_HIS_INSTANT_METER_CREATED
    ON HIS_INSTANT_METER (CREATED);
  PRINT 'Created IX_HIS_INSTANT_METER_CREATED';
END

-- INFO_METER: tối ưu filter theo STATE và REGION_ID
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'IX_INFO_METER_STATE_REGION'
    AND object_id = OBJECT_ID('INFO_METER')
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_INFO_METER_STATE_REGION
    ON INFO_METER (STATE, REGION_ID)
    INCLUDE (METER_NO, METER_NAME, ADDRESS);
  PRINT 'Created IX_INFO_METER_STATE_REGION';
END

PRINT 'Done. Indexes created successfully.';
